export const listCodeCountry = [
  { value: "", label: "All Country" },
  { value: "ae", label: "United Arab Emirates" },
  { value: "ar", label: "Argentina" },
  { value: "at", label: "Austria" },
  { value: "au", label: "Australia" },
  { value: "be", label: "Belgium" },
  { value: "bg", label: "Bulgaria" },
  { value: "br", label: "Brazil" },
  { value: "ca", label: "Canada" },
  { value: "ch", label: "Switzerland" },
  { value: "cn", label: "China" },
  { value: "co", label: "Colombia" },
  { value: "cu", label: "Cuba" },
  { value: "cz", label: "Czech Republic" },
  { value: "de", label: "Germany" },
  { value: "eg", label: "Egypt" },
  { value: "fr", label: "France" },
  { value: "gb", label: "United Kingdom" },
  { value: "gr", label: "Greece" },
  { value: "hk", label: "Hong Kong" },
  { value: "hu", label: "Hungary" },
  { value: "id", label: "Indonesia" },
  { value: "ie", label: "Ireland" },
  { value: "il", label: "Israel" },
  { value: "in", label: "India" },
  { value: "it", label: "Italy" },
  { value: "jp", label: "Japan" },
  { value: "kr", label: "South Korea" },
  { value: "lt", label: "Lithuania" },
  { value: "lv", label: "Latvia" },
  { value: "ma", label: "Morocco" },
  { value: "mx", label: "Mexico" },
  { value: "my", label: "Malaysia" },
  { value: "ng", label: "Nigeria" },
  { value: "nl", label: "Netherlands" },
  { value: "no", label: "Norway" },
  { value: "nz", label: "New Zealand" },
  { value: "ph", label: "Philippines" },
  { value: "pl", label: "Poland" },
  { value: "pt", label: "Portugal" },
  { value: "ro", label: "Romania" },
  { value: "rs", label: "Serbia" },
  { value: "ru", label: "Russia" },
  { value: "sa", label: "Saudi Arabia" },
  { value: "se", label: "Sweden" },
  { value: "sg", label: "Singapore" },
  { value: "si", label: "Slovenia" },
  { value: "sk", label: "Slovakia" },
  { value: "th", label: "Thailand" },
  { value: "tr", label: "Turkey" },
  { value: "tw", label: "Taiwan" },
  { value: "ua", label: "Ukraine" },
  { value: "us", label: "United States" },
  { value: "ve", label: "Venezuela" },
  { value: "za", label: "South Africa" },
];

export const listCodeCategory = [
  {
    value: "",
    label: "All Category",
  },
  {
    value: "business",
    label: "Business",
  },
  {
    value: "entertainment",
    label: "Entertainment",
  },
  {
    value: "general",
    label: "General",
  },
  {
    value: "health",
    label: "Health",
  },
  {
    value: "science",
    label: "Science",
  },
  {
    value: "sports",
    label: "Sports",
  },
  {
    value: "technology",
    label: "Technology",
  },
];

export const provinceCoordinates = [
  { name: "Aceh", lat: 4.36855, lon: 97.0253 },
  { name: "Sumatera Utara", lat: 3.5852, lon: 98.6756 },
  { name: "Sumatera Barat", lat: -0.9471, lon: 100.4172 },
  { name: "Riau", lat: 0.5071, lon: 101.4478 },
  { name: "Kepulauan Riau", lat: 3.9457, lon: 108.1429 },
  { name: "Jambi", lat: -1.4852, lon: 102.4381 },
  { name: "Bengkulu", lat: -3.7928, lon: 102.2605 },
  { name: "Sumatera Selatan", lat: -3.3194, lon: 104.9149 },
  { name: "Bangka Belitung", lat: -2.7411, lon: 106.4406 },
  { name: "Lampung", lat: -5.45, lon: 105.2667 },
  { name: "Banten", lat: -6.1206, lon: 106.1506 },
  { name: "DKI Jakarta", lat: -6.2088, lon: 106.8456 },
  { name: "Jawa Barat", lat: -6.9039, lon: 107.6186 },
  { name: "Jawa Tengah", lat: -7.0051, lon: 110.4381 },
  { name: "DI Yogyakarta", lat: -7.7956, lon: 110.3695 },
  { name: "Jawa Timur", lat: -7.2504, lon: 112.7688 },
  { name: "Bali", lat: -8.4095, lon: 115.1889 },
  { name: "Nusa Tenggara Barat", lat: -8.6529, lon: 117.3616 },
  { name: "Nusa Tenggara Timur", lat: -8.6574, lon: 121.0794 },
  { name: "Kalimantan Barat", lat: 0.1322, lon: 111.0969 },
  { name: "Kalimantan Tengah", lat: -1.6815, lon: 113.3824 },
  { name: "Kalimantan Selatan", lat: -3.0926, lon: 115.2838 },
  { name: "Kalimantan Timur", lat: 0.5387, lon: 116.4194 },
  { name: "Kalimantan Utara", lat: 3.0731, lon: 117.8903 },
  { name: "Sulawesi Utara", lat: 1.4931, lon: 124.8413 },
  { name: "Gorontalo", lat: 0.6999, lon: 122.4467 },
  { name: "Sulawesi Tengah", lat: -1.43, lon: 121.4456 },
  { name: "Sulawesi Barat", lat: -2.8445, lon: 119.2321 },
  { name: "Sulawesi Selatan", lat: -3.6688, lon: 119.9741 },
  { name: "Sulawesi Tenggara", lat: -4.1432, lon: 122.1746 },
  { name: "Maluku", lat: -3.2385, lon: 130.1453 },
  { name: "Maluku Utara", lat: 1.57, lon: 127.8088 },
  { name: "Papua Barat Daya", lat: -1.3361, lon: 131.4886 },
  { name: "Papua Barat", lat: -0.8629, lon: 134.062 },
  { name: "Papua", lat: -4.2699, lon: 138.0804 },
  { name: "Papua Tengah", lat: -3.995, lon: 136.0826 },
  { name: "Papua Pegunungan", lat: -4.2325, lon: 138.8 },
  { name: "Papua Selatan", lat: -6.21, lon: 139.5 },
];
